#define constants
ROOT_FOLDER = ''
TRAIN_EMBED_PATH = ROOT_FOLDER+'data/entube_embedding_train.pt'
VAL_EMBED_PATH = ROOT_FOLDER+'data/entube_embedding_val.pt'
TEST_EMBED_PATH = ROOT_FOLDER+'data/entube_embedding_test.pt'

SELECT_LABEL = 'label_2'
SAVING_FOLDER = 'trying'
VERSION_MODEL = 'model_main'
CHECKPOINT_DIR = f'{ROOT_FOLDER}checkpoints/{VERSION_MODEL}/{SELECT_LABEL}/{SAVING_FOLDER}'
LOG_DIR = f'{ROOT_FOLDER}logs/{VERSION_MODEL}/{SELECT_LABEL}/{SAVING_FOLDER}'

PATIENCE = 15
BATCH_SIZE = 32
NUM_EPOCH = 30

INPUT_SAME = 512
INPUT_TEXT = 768
INPUT_THUMBNAIL = 2560
INPUT_VIDEO = 2304*2*2
INPUT_AUDIO = 62*128
INPUT_SUM = INPUT_TEXT*2+INPUT_THUMBNAIL+INPUT_VIDEO+INPUT_AUDIO
